-- ─── GENESIS schema ────────────────────────────────────────────────
-- Run with the Supabase CLI (`supabase db push`) or paste into the SQL editor.
-- Identity lives in Supabase Auth (auth.users). These tables hold app data
-- keyed by the auth user id.

-- One profile per user, created on signup. Holds the Stripe customer link.
create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  email text not null,
  full_name text,
  stripe_customer_id text unique,
  created_at timestamptz not null default now()
);

-- Current subscription state, synced from Stripe webhooks.
create table if not exists public.subscriptions (
  user_id uuid primary key references auth.users (id) on delete cascade,
  plan text not null default 'free'
    check (plan in ('free','starter','pro','business','enterprise','agency')),
  status text not null default 'inactive',
  stripe_subscription_id text unique,
  stripe_price_id text,
  current_period_end timestamptz,
  updated_at timestamptz not null default now()
);

-- Every site generated by a user (for usage limits + dashboard listing).
create table if not exists public.sites (
  id text primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  business_name text not null,
  type text not null,
  sector text,
  language text,
  status text not null default 'building'
    check (status in ('building','live','failed')),
  deploy_url text,
  created_at timestamptz not null default now()
);

create index if not exists sites_user_created_idx
  on public.sites (user_id, created_at desc);

-- ─── Row Level Security ────────────────────────────────────────────
-- The server uses the service-role key (bypasses RLS). These policies let a
-- logged-in user read their own rows directly from the browser if you ever
-- query client-side.
alter table public.profiles enable row level security;
alter table public.subscriptions enable row level security;
alter table public.sites enable row level security;

create policy "own profile" on public.profiles
  for select using (auth.uid() = id);
create policy "own subscription" on public.subscriptions
  for select using (auth.uid() = user_id);
create policy "own sites" on public.sites
  for select using (auth.uid() = user_id);
